server:
  port: 8201
spring:
  application:
    name: why-gateway
  profiles:
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true #service-id
      routes:
        - id: why-system
          uri: lb://why-system
          predicates:
            - Path=/why-system/**
          filters:
            - StripPrefix=1
        - id: why-tools
          uri: lb://why-tools
          predicates:
            - Path=/why-tools/**
          filters:
            - StripPrefix=1
        - id: why-logging
          uri: lb://why-logging
          predicates:
            - Path=/why-logging/**
          filters:
            - StripPrefix=1
    nacos:
      discovery:
        server-addr: http://10.211.55.140:8848
      config:
        server-addr: http://10.211.55.140:8848
        file-extension: yaml

  #配置 Jpa
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        enable_lazy_no_trans: true
    #        指定表名解析。spring下可不加。会自动使用
        naming:
          physical-strategy: com.lwohvye.sys.config.common.ServerAwareNamingStrategy
    open-in-view: true
    hibernate:
      ddl-auto: none
feign:
  httpclient:
    enabled: true

rsa:
  private_key: MIIEugIBADANBgkqhkiG9w0BAQEFAASCBKQwggSgAgEAAoIBAQC0puTIfyD5bzz7MJqqfn424Qz2OhWGck/9gDpf3ZFZ4CMRc9TUMafeMJUSeziuRJBSvJ8Ru1SE0CjAgGasm6DDm0Ad8ryd8pWwMu0HFyo0R++D2+5G75/e6h7+UG5r28XmUVgmpbP6cgyrnUlR4EQiimuWV7Jr4oHQ2LqG59UnOfMxTE+pSMgMqXTMtTJXOkTKd9vAEDyAmD9jIDTPJGfOX4470pPgX+RPJpxls0k7PVrh9xMhxXGS/8nWu3kENSweLNBrnzLbNXD2bzRYq7lvuTgymMhCKTTy9JqflLmI3s/2wxN3G8CkBpn3xm6Tw7EHlA4XY3HHVQGovvuXpE2HAgMBAAECggEAAmgKuiT/YnM547q1BLpkogSDcLA7YywYpq7TmD1SV1kl/nCFkEINE2egRLvBeIjPR1rd35WYPaCsOkw7kecM0C48P2nhW1VE6zDyeVq0pDelGCOQ2/8LKSQDP64Amo016KiCvRkN+bMVOiABPwb2wWMIpdsLNGazBf4tFej2rOwR5YTxBjRUsb55ID/SRSCpPT/1QAlGIv+UjX+jecIJqygkEXcCzClePN+sGBkOyBftZ7qlBrsU/FSeWb+McT2sqKBDA5tQNy0Q631MPAsGMKBYAcY52fmZcaVcmN21DnvIRinShSrO6+JeTbAeOSc4Hxnty4mqKti2i1v0Ua3XwQKBgQD7gfkhRr3Yt5JUbuUSOpTuDqsQmri7SFQ/dYfBHgHXGuZG1lNAF6VMaPkbgzjAoLx9SWvAzsoS+VsLPEpbzBYlFFS0fab0T50TOVEWwdnROCo8CGjPTgf9g8WGw6QN1IeHUr443Ae+2D9vx/BxsmZekAydi27Hy1PD5HcEDOoEJwKBgQC34O4li34P3DnEXrVJxGZ6PfECRukx9vSpsSGyVFHyABDRoQCR5pdJiF3l08WjiZSo6cHvr1JAkYx/vfQjJVHJqa8pKfz9AkaGCw5ciUFFRvGfLCv6EVJbuW5YtENjN8KuaVekEN1wJSG4r5DPDhnLxmV0ONVfpPJ27Xtg7FRnoQJ/TKFNRtZHAcDs1Mz0/pjax62wcV6y6l0fTjaBJlX+OYv4nZyvwNdzhdR2EevpXseappG4Qwa+iwlus/2qqk2EccfABz5BoC6hrTnJeyWVOCnktGXbiU49IQEFLgpt8cjPgmuziZ+AvKUmrug8WmgAyM8bCOVy220YGJeDq7hDlQKBgE3DbnOqXpHOjQ+jDgA4cy5Xa8mOu6hJzIbHRnzodA9oP7Sn5lnNr0WFylAcE4Vp9djJox7+gkaUR1rutoT2j3Q9srox67AEelbN7jDsSxJFQoISaDbFhJMOBMC225jmSAsCufHEwCFhUrWMai1mxToMmXNhZbuhQnlRTdBbogaBAoGAae8hgwu4VgIrEBHvkhVsBDK2wib6JjbrTbWZh8LwMOUdTZEUNfHaXyXjkpDmJ/HkDQ8IgmOn4ZXSIv9kqr+BAepC+lhOE8m6FbE0vFXeW2izFcWLXH3d4GTL8QCKAgZdWd/iF2cBt/puJgy+B6Ym4izwre3qSG+DhqpoQ3ogtis=
  public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtKbkyH8g+W88+zCaqn5+NuEM9joVhnJP/YA6X92RWeAjEXPU1DGn3jCVEns4rkSQUryfEbtUhNAowIBmrJugw5tAHfK8nfKVsDLtBxcqNEfvg9vuRu+f3uoe/lBua9vF5lFYJqWz+nIMq51JUeBEIoprlleya+KB0Ni6hufVJznzMUxPqUjIDKl0zLUyVzpEynfbwBA8gJg/YyA0zyRnzl+OO9KT4F/kTyacZbNJOz1a4fcTIcVxkv/J1rt5BDUsHizQa58y2zVw9m80WKu5b7k4MpjIQik08vSan5S5iN7P9sMTdxvApAaZ98Zuk8OxB5QOF2Nxx1UBqL77l6RNhwIDAQAB

local:
  sys:
    load-os: true
#    unauth: true
    sp-sync-queue: gateway.sp-sync.queue
